AndreAirlineMVC/Models/ErrorViewModel.cs
using System;

namespace AndreAirlineMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AndreAirlineMVC/Controllers/AeroportoController.cs
using AndreAirlineApi2.Data.Repositorios;
using Microsoft.AspNetCore.Mvc;

namespace AndreAirlineMVC.Controllers
{
    public class AeroportoController : Controller
    {
        private readonly RepositorioAeroportoImplementation _respositoy;

        public AeroportoController(RepositorioAeroportoImplementation respositoy)
        {
            _respositoy = respositoy;
        }

        public IActionResult Index()
        {
            return View(_respositoy.List(orderBy: p => p.Sigla));
        }
    }
}

AndreAirlineMVC/Controllers/AirportDatasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AndreAirlineApi2.Model;
using AndreAirlineMVC.Data;

namespace AndreAirlineMVC.Controllers
{
    public class AirportDatasController : Controller
    {
        private readonly AndreAirlineMVCContext _context;

        public AirportDatasController(AndreAirlineMVCContext context)
        {
            _context = context;
        }

        // GET: AirportDatas
        public async Task<IActionResult> Index()
        {
            return View(await _context.AirportData.ToListAsync());
        }
    }
}

AndreAirlineMVC/Controllers/HomeController.cs
using AndreAirlineMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace AndreAirlineMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AndreAirlineMVC/Views/Aeroporto/Index.cshtml
@model IEnumerable<AndreAirlineApi2.Model.Aeroporto>

@{
  ViewData["Title"] = "Index";
}

<h1>Index</h1>

<table class="table">
  <thead>
    <tr>
      <th>
        @Html.DisplayNameFor(model => model.Sigla)
      </th>
      <th>
        @Html.DisplayNameFor(model => model.Nome)
      </th>
      <th>
        @Html.DisplayNameFor(model => model.LoginUser)
      </th>
    </tr>
  </thead>
  <tbody>
    @foreach (var item in Model)
    {
      <tr>
        <td>
          @Html.DisplayFor(modelItem => item.Sigla)
        </td>
        <td>
          @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
          @Html.DisplayFor(modelItem => item.LoginUser)
        </td>
      </tr>
    }
  </tbody>
</table>

AndreAirlineMVC/Views/AirportDatas/Index.cshtml
@model IEnumerable<AndreAirlineApi2.Model.AirportData>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Code)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Country)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Continent)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Country)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Continent)
            </td>
        </tr>}
    </tbody>
</table>

AndreAirlineMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AndreAirlineMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AndreAirlineMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AndreAirlineMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Aeroporto" asp-action="Index">Aeroporto</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AirportDatas" asp-action="Index">AirportData</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - AndreAirlineMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>